wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1646419825
    t:
      1:
      - 2
      - 3
      - 5
      - 6
      2:
      - 2
      - 3
      - 5
      - 6
      3:
      - 3
      - 8
      - 19
      4: 3.9.6
      5: 0.12.11
      8:
      - 3
      - 5
all_data:
  desc: null
  value: true
epochs:
  desc: null
  value: 10
mc_dropout:
  desc: null
  value: false
