RNN_params:
  lr: 0.0033
  activation: 'relu'
  dropout: 0.2810
  redropout: 0.0794
  merged_layer_units:
    - 300
  clipnorm: 0.001
  lstm_units: 140
  output_units: 179
  asimov_batch_size: 4096
  cross_entropy_batch_size: 128
  systematic_uncertainty: 0.05
  monitor: val_AUC
  mode: max

FNN_params:
  lr: 0.0004
  activation: 'relu'
  dropout: 0.01
  hidden_layer_units:
    - 350
    - 71
    - 84
  clipnorm: 0.001
  asimov_batch_size: 4096
  cross_entropy_batch_size: 64
  systematic_uncertainty: 0.05
  monitor: val_AUC
  mode: max

XGBoost_params:
  lr: 0.15, 
  max_depth: 10,
  alpha: 5,
  colsample_bytree: 0.7,
  reg_lambda: 0.23,
  min_child_weight: 4,
  subsample: 1,
  scale_pos_weight: scale_factor
  early_stopping_rounds: 20

visuals:
  style: 
    - 'science'
    - 'notebook'
  shap_n_bg: 10
  shap_n_values: 500

paths:
  interim_path: data/interim
  fig_path: reports/figures
  raw_path: data/raw
  processed_path: data/processed

data:
  lum: 140_000

  event_cols:
    - BiasedDPhi
    - DiJet_mass
    - HT
    - InputMet_InputJet_mindPhi
    - InputMet_pt
    - MHT_pt
    - MinChi
    - MinOmegaHat
    - MinOmegaTilde
    - ncleanedBJet
    - ncleanedJet

  object_cols:
    - cleanedJet_pt
    - cleanedJet_area
    - cleanedJet_btagDeepB
    - cleanedJet_chHEF
    - cleanedJet_eta
    - cleanedJet_mass
    - cleanedJet_neHEF
    - cleanedJet_phi

  useful_cols:
    - signal
    - xs_weight

  untransformed_cols: 
    - ncleanedBJet
    - ncleanedJet
    - BiasedDPhi
    - signal
